/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardClassroomRouteImport } from './routes/dashboard/classroom'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as DashboardCommunityIndexRouteImport } from './routes/dashboard/community/index'
import { Route as DashboardCommunityCreatePostRouteImport } from './routes/dashboard/community/create-post'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardCommunityPostPostIdIndexRouteImport } from './routes/dashboard/community/post/$postId/index'
import { Route as DashboardCommunityPostPostIdEditRouteImport } from './routes/dashboard/community/post/$postId/edit'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassroomRoute = DashboardClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCommunityIndexRoute = DashboardCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityCreatePostRoute =
  DashboardCommunityCreatePostRouteImport.update({
    id: '/community/create-post',
    path: '/community/create-post',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCommunityPostPostIdIndexRoute =
  DashboardCommunityPostPostIdIndexRouteImport.update({
    id: '/community/post/$postId/',
    path: '/community/post/$postId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCommunityPostPostIdEditRoute =
  DashboardCommunityPostPostIdEditRouteImport.update({
    id: '/community/post/$postId/edit',
    path: '/community/post/$postId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/classroom': typeof DashboardClassroomRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/community/create-post': typeof DashboardCommunityCreatePostRoute
  '/dashboard/community': typeof DashboardCommunityIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/dashboard/community/post/$postId/edit': typeof DashboardCommunityPostPostIdEditRoute
  '/dashboard/community/post/$postId': typeof DashboardCommunityPostPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/classroom': typeof DashboardClassroomRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/community/create-post': typeof DashboardCommunityCreatePostRoute
  '/dashboard/community': typeof DashboardCommunityIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/dashboard/community/post/$postId/edit': typeof DashboardCommunityPostPostIdEditRoute
  '/dashboard/community/post/$postId': typeof DashboardCommunityPostPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/classroom': typeof DashboardClassroomRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/community/create-post': typeof DashboardCommunityCreatePostRoute
  '/dashboard/community/': typeof DashboardCommunityIndexRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/dashboard/community/post/$postId/edit': typeof DashboardCommunityPostPostIdEditRoute
  '/dashboard/community/post/$postId/': typeof DashboardCommunityPostPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/calendar'
    | '/dashboard/classroom'
    | '/dashboard/members'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/dashboard/community/create-post'
    | '/dashboard/community'
    | '/profile/$userId'
    | '/dashboard/community/post/$postId/edit'
    | '/dashboard/community/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/calendar'
    | '/dashboard/classroom'
    | '/dashboard/members'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/dashboard/community/create-post'
    | '/dashboard/community'
    | '/profile/$userId'
    | '/dashboard/community/post/$postId/edit'
    | '/dashboard/community/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/calendar'
    | '/dashboard/classroom'
    | '/dashboard/members'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/dashboard/community/create-post'
    | '/dashboard/community/'
    | '/profile/$userId/'
    | '/dashboard/community/post/$postId/edit'
    | '/dashboard/community/post/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classroom': {
      id: '/dashboard/classroom'
      path: '/classroom'
      fullPath: '/dashboard/classroom'
      preLoaderRoute: typeof DashboardClassroomRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/community/': {
      id: '/dashboard/community/'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community/create-post': {
      id: '/dashboard/community/create-post'
      path: '/community/create-post'
      fullPath: '/dashboard/community/create-post'
      preLoaderRoute: typeof DashboardCommunityCreatePostRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/community/post/$postId/': {
      id: '/dashboard/community/post/$postId/'
      path: '/community/post/$postId'
      fullPath: '/dashboard/community/post/$postId'
      preLoaderRoute: typeof DashboardCommunityPostPostIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community/post/$postId/edit': {
      id: '/dashboard/community/post/$postId/edit'
      path: '/community/post/$postId/edit'
      fullPath: '/dashboard/community/post/$postId/edit'
      preLoaderRoute: typeof DashboardCommunityPostPostIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardClassroomRoute: typeof DashboardClassroomRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCommunityCreatePostRoute: typeof DashboardCommunityCreatePostRoute
  DashboardCommunityIndexRoute: typeof DashboardCommunityIndexRoute
  DashboardCommunityPostPostIdEditRoute: typeof DashboardCommunityPostPostIdEditRoute
  DashboardCommunityPostPostIdIndexRoute: typeof DashboardCommunityPostPostIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardClassroomRoute: DashboardClassroomRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCommunityCreatePostRoute: DashboardCommunityCreatePostRoute,
  DashboardCommunityIndexRoute: DashboardCommunityIndexRoute,
  DashboardCommunityPostPostIdEditRoute: DashboardCommunityPostPostIdEditRoute,
  DashboardCommunityPostPostIdIndexRoute:
    DashboardCommunityPostPostIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
